version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - '3001:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - notifications

  notifications:
    build: ./notifications
    ports:
      - '3002:3001'
    env_file:
      - ./notifications/.env

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
