version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - backend-persons
      - backend-computers
      - backend-reservations

  backend-persons:
    build: ./backend-persons
    ports:
      - "3002:3001"
    env_file:
      - ./backend-persons/.env
    depends_on:
      - postgres

  backend-computers:
    build: ./backend-computers
    ports:
      - "3004:3001"
    env_file:
      - ./backend-computers/.env

  backend-reservations:
    build: ./backend-reservations
    ports:
      - "3005:3001"
    env_file:
      - ./backend-reservations/.env

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
