apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-persons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-persons
  template:
    metadata:
      labels:
        app: backend-persons
    spec:
      containers:
        - name: backend-persons
          image: backend-persons:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: backend-persons-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend-persons
spec:
  type: NodePort
  selector:
    app: backend-persons
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
