apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: admin
  DB_NAME: mydb
  NOTIFICATION_SERVICE_URL: http://notifications:3001

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_BACKEND_URL: http://backend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  PORT: "3001"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: admin
