apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: notifications:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: notifications-config

---
apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  type: NodePort
  selector:
    app: notifications
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30002
